BOLD="1"
LIGHT="0"
BOLDRED="\[\e[${BOLD};31m\]"
BOLDGREEN="\[\e[${BOLD};32m\]"
BOLDYELLOW="\[\e[${BOLD};33m\]"
BOLDBLUE="\[\e[${BOLD};34m\]"
BOLDMAGENTA="\[\e[${BOLD};35m\]"
LIGHTRED="\[\e[${LIGHT};31m\]"
LIGHTGREEN="\[\e[${LIGHT};32m\]"
LIGHTYELLOW="\[\e[${LIGHT};33m\]"
LIGHTBLUE="\[\e[${LIGHT};34m\]"
LIGHTMAGENTA="\[\e[${LIGHT};35m\]"
LIGHTGRAY="\[\e[${LIGHT};37m\]"
USERCOLOR="\$(test `id -u` -eq 0 && echo \"${BOLDRED}\" || echo \"${BOLDGREEN}\")"
NORMALCOLOR="\[\e[m\]"
SMILEY="${BOLDGREEN}:)"
FROWNY="${BOLDRED}:("

